### PR TITLE
relative paths

### PR DESCRIPTION
**Pull request by hjone72**
This should make relative paths work.

### CODE REVIEW

**Comment by JasonHHouse** [comment]
I think this works for people who run Gaps on the same machine as Plex but would not work for those running on different machines. I won't be able to test that for a bit but I wanted to see your thoughts if that's the case.

**Comment by hjone72** [comment]
These ajax calls are internal to gaps and from what I can see should only affect the various pages. I haven't adjusted the internal calls out to Plex.

When you say Plex running on the same machine, does going via a docker still count?

I'm not sure if the websocket is working correctly under this change though. I'll do some more testing and report back.

**Comment by JasonHHouse** [comment]
You're right, that was my bad. I was thinking this was something else. This should be fine then. The code changes seem fine, I just want to test on my machine when I get home before merging. 

You also caught a bug. :) The PUT http call should have been changed to https.

**Comment by JasonHHouse** [comment]
So it works, but I'm noticing one issue. I'm not getting the dynamic updates over the WS anymore. I only get all the results at the end. Are you seeing that?

@Knoxie Can you test this PR out as well?

**Comment by Knoxie** [comment]
> So it works, but I'm noticing one issue. I'm not getting the dynamic updates over the WS anymore. I only get all the results at the end. Are you seeing that?
> 
> @Knoxie Can you test this PR out as well?

Getting same issue. This kills the updates while doing the search. Movies no longer show up while doing the search. 

This is not acceptable as it stops the user from seeing progress.

**Pull request merged**
